/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serliogiron_lab7p2;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Artist = new javax.swing.JFrame();
        TabbedPane = new javax.swing.JTabbedPane();
        Single = new javax.swing.JPanel();
        field_title_single = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        field_nombre_cancion_single = new javax.swing.JTextField();
        field_duracion_single = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Lanzar_single = new javax.swing.JButton();
        Album = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TITLE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombre_cancion = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        Agregar_cancion = new javax.swing.JButton();
        Publicar_album = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_album_artista = new javax.swing.JTree();
        User = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        contra_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario_field = new javax.swing.JTextField();
        LOGIN = new javax.swing.JButton();
        tabbedpanel = new javax.swing.JTabbedPane();
        user = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        register_user = new javax.swing.JButton();
        user_register_password = new javax.swing.JPasswordField();
        user_register_username = new javax.swing.JTextField();
        user_register_age = new javax.swing.JFormattedTextField();
        artist = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        artist_register_username1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        artist_register_password1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        artist_register_age1 = new javax.swing.JFormattedTextField();
        artist_register = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        artist_artisticname_field = new javax.swing.JTextField();

        TabbedPane.setBackground(new java.awt.Color(102, 255, 102));

        jLabel13.setText("TITLE");

        field_nombre_cancion_single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nombre_cancion_singleActionPerformed(evt);
            }
        });

        field_duracion_single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_duracion_singleActionPerformed(evt);
            }
        });

        jLabel14.setText("Duracion");

        jLabel15.setText("Nombre de cancion");

        Lanzar_single.setText("Lanzar Single");
        Lanzar_single.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lanzar_singleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SingleLayout = new javax.swing.GroupLayout(Single);
        Single.setLayout(SingleLayout);
        SingleLayout.setHorizontalGroup(
            SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SingleLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Lanzar_single)
                        .addGap(80, 80, 80))
                    .addGroup(SingleLayout.createSequentialGroup()
                        .addGroup(SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SingleLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(67, 67, 67)
                                .addComponent(field_duracion_single))
                            .addGroup(SingleLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(field_nombre_cancion_single)))
                        .addContainerGap())))
            .addGroup(SingleLayout.createSequentialGroup()
                .addGroup(SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SingleLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(field_title_single, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SingleLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SingleLayout.setVerticalGroup(
            SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingleLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_title_single, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(field_nombre_cancion_single, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(field_duracion_single, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Lanzar_single)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Single", Single);

        jLabel10.setText("TITLE");

        jLabel11.setText("Nombre de cancion");

        jLabel12.setText("Duracion");

        nombre_cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_cancionActionPerformed(evt);
            }
        });

        duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionActionPerformed(evt);
            }
        });

        Agregar_cancion.setText("Agregar Cancion");
        Agregar_cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_cancionMouseClicked(evt);
            }
        });

        Publicar_album.setText("Publicar Album");
        Publicar_album.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Publicar_albumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AlbumLayout = new javax.swing.GroupLayout(Album);
        Album.setLayout(AlbumLayout);
        AlbumLayout.setHorizontalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AlbumLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(67, 67, 67)
                                .addComponent(duracion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AlbumLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_cancion))))
                    .addGroup(AlbumLayout.createSequentialGroup()
                        .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Agregar_cancion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Publicar_album))
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AlbumLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AlbumLayout.setVerticalGroup(
            AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombre_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar_cancion)
                    .addComponent(Publicar_album))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Album", Album);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamiento");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Single");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        treeNode1.add(treeNode2);
        jTree_album_artista.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree_album_artista);

        javax.swing.GroupLayout ArtistLayout = new javax.swing.GroupLayout(Artist.getContentPane());
        Artist.getContentPane().setLayout(ArtistLayout);
        ArtistLayout.setHorizontalGroup(
            ArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistLayout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
        ArtistLayout.setVerticalGroup(
            ArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User.getContentPane());
        User.getContentPane().setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        LOGIN.setBackground(new java.awt.Color(0, 0, 255));
        LOGIN.setText("LOG IN");
        LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINMouseClicked(evt);
            }
        });

        tabbedpanel.setBackground(new java.awt.Color(0, 0, 0));

        user.setBackground(new java.awt.Color(51, 255, 51));

        jLabel3.setText("USERNAME");

        jLabel4.setText("PASSOWRD");

        jLabel5.setText("AGE");

        register_user.setText("Register");
        register_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_userMouseClicked(evt);
            }
        });

        user_register_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_register_usernameActionPerformed(evt);
            }
        });

        user_register_age.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_register_password)
                    .addComponent(register_user)
                    .addComponent(user_register_username)
                    .addComponent(user_register_age, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(user_register_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(user_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(user_register_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(register_user)
                .addGap(74, 74, 74))
        );

        tabbedpanel.addTab("USER", user);

        artist.setBackground(new java.awt.Color(51, 255, 51));
        artist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("USERNAME");

        artist_register_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist_register_username1ActionPerformed(evt);
            }
        });

        jLabel7.setText("PASSOWRD");

        jLabel8.setText("AGE");

        artist_register_age1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        artist_register.setText("Register");
        artist_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artist_registerMouseClicked(evt);
            }
        });

        jLabel9.setText("ARTISTIC NAME");

        artist_artisticname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist_artisticname_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout artistLayout = new javax.swing.GroupLayout(artist);
        artist.setLayout(artistLayout);
        artistLayout.setHorizontalGroup(
            artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(artist_register_password1)
                    .addComponent(artist_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artist_register_username1)
                    .addComponent(artist_register_age1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artist_artisticname_field))
                .addGap(104, 104, 104))
        );
        artistLayout.setVerticalGroup(
            artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artistLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(artist_register_username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(artist_register_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(artist_register_age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(artistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(artist_artisticname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(artist_register)
                .addGap(74, 74, 74))
        );

        tabbedpanel.addTab("ARTIST", artist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabbedpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuario_field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contra_field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(LOGIN)
                .addGap(256, 256, 256))
            .addComponent(tabbedpanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_register_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_register_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_register_usernameActionPerformed

    private void artist_register_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist_register_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artist_register_username1ActionPerformed

    private void artist_artisticname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist_artisticname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artist_artisticname_fieldActionPerformed

    private void register_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_userMouseClicked
        String username;
        String password;
        int age;
        
        username = user_register_username.getText();
        password = user_register_password.getText();
        age = Integer.parseInt(user_register_age.getText());
        
        user_register_username.setText("");
        user_register_password.setText("");
        user_register_age.setText("");
        
        UserNormal usuario = new UserNormal();
        
        usuario.setEdad(age);
        usuario.setPassword(password);
        usuario.setUsername(username);
        
        cuentas.add(usuario);
        
        usuarioMain = usuario;
        
        User.pack();
        User.setVisible(true);
    }//GEN-LAST:event_register_userMouseClicked

    private void artist_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artist_registerMouseClicked
        String username;
        String password;
        int age;
        String nombreart;
        
        username = artist_register_username1.getText();
        password = artist_register_password1.getText();
        age = Integer.parseInt(artist_register_age1.getText());
        nombreart = artist_artisticname_field.getText();
        
        user_register_username.setText("");
        user_register_password.setText("");
        user_register_age.setText("");
        artist_artisticname_field.setText("");
        
        Artista usuario = new Artista();
        
        usuario.setEdad(age);
        usuario.setPassword(password);
        usuario.setUsername(username);
        usuario.setNombre_art(nombreart);
        
        cuentas.add(usuario);
        
        usuarioMain = usuario;
        
        Artist.pack();
        Artist.setVisible(true);
    }//GEN-LAST:event_artist_registerMouseClicked

    private void nombre_cancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_cancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_cancionActionPerformed

    private void duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionActionPerformed

    private void field_nombre_cancion_singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nombre_cancion_singleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nombre_cancion_singleActionPerformed

    private void field_duracion_singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_duracion_singleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_duracion_singleActionPerformed

    private void Agregar_cancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_cancionMouseClicked
        
        Cancion cancion = new Cancion();
        
        String titulo = nombre_cancion.getText();
        double dura = Double.parseDouble(duracion.getText());
        
        cancion.setTitulo(titulo);
        cancion.setDuracion(dura);
        
        canciones.add(cancion);
        
        nombre_cancion.setText("");
        duracion.setText("");
    }//GEN-LAST:event_Agregar_cancionMouseClicked
    
    ArrayList <Cancion> canciones = new ArrayList();
    ArrayList <Album> albumes = new ArrayList();
    
    private void Publicar_albumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Publicar_albumMouseClicked
        /*for (int i = 0; i < canciones.size(); i++) {
        System.out.println(canciones.get(i));
        }*/
        
        Album album = new Album();
        
        String titulo;
        Date fecha;
        int likes;
        
        titulo = TITLE.getText();
        fecha = new Date();
        likes = 0;
        
        album.setTitulo(titulo);
        album.setFecha(fecha);
        album.setLikes(likes);
        
        for (int i = 0; i < canciones.size(); i++) 
        {
            canciones.get(i).setAlbum(album);
        }
        
        album.setCanciones(canciones);
        album.setCanciones_cant(canciones.size());
        
        //System.out.println(album);
        
        ((Artista) usuarioMain).setCanciones(canciones);
        //System.out.println("ola");
        ((Artista) usuarioMain).getAlbumes().add(album);
        
        //canciones.clear();
        
        nombre_cancion.setText("");
        duracion.setText("");
        TITLE.setText("");
        
        //System.out.println("llega hasta aqui");
        
        DefaultTreeModel modelo;
        modelo = (DefaultTreeModel) jTree_album_artista.getModel();
        
        DefaultMutableTreeNode raiz; 
        raiz = (DefaultMutableTreeNode) modelo.getChild(modelo.getRoot(), 1);
        
        DefaultMutableTreeNode nodo_album; 
        nodo_album = new DefaultMutableTreeNode(album);
        
        DefaultMutableTreeNode cancion; 
        System.out.println("Size> "+album.getCanciones().size());
        for (int i = 0; i < album.getCanciones().size(); i++) 
        {
            //System.out.println("HOLAAAA> "+album.getCanciones().get(i).toString());
            cancion = new DefaultMutableTreeNode(album.getCanciones().get(i));
            nodo_album.add(cancion);
        }
        
        raiz.add(nodo_album);
        modelo.reload();
        canciones.clear();
    }//GEN-LAST:event_Publicar_albumMouseClicked

    private void LOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseClicked
        Artist.pack();
        Artist.setVisible(true);
    }//GEN-LAST:event_LOGINMouseClicked

    private void Lanzar_singleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanzar_singleMouseClicked
        Single single = new Single();
        
        String titulo = field_title_single.getText();
        single.setTitulo(titulo);
        
        Cancion cancion = new Cancion();
        
        String nombre = field_nombre_cancion_single.getText();
        double duracion = Double.parseDouble(field_duracion_single.getText());
        
        cancion.setAlbum(single);
        cancion.setDuracion(duracion);
        cancion.setTitulo(nombre);
        
        single.setCancion(cancion);
        
        //System.out.println(cancion);
        
        DefaultTreeModel modelo;
        modelo = (DefaultTreeModel) jTree_album_artista.getModel();
        
        DefaultMutableTreeNode raiz; 
        raiz = (DefaultMutableTreeNode) modelo.getChild(modelo.getRoot(), 0);
        
        DefaultMutableTreeNode nodo_single; 
        nodo_single = new DefaultMutableTreeNode(single);
        
        raiz.add(nodo_single);
        modelo.reload();
    }//GEN-LAST:event_Lanzar_singleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    //variables mias
    Usuario usuarioMain;
    ArrayList <Usuario> cuentas = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_cancion;
    private javax.swing.JPanel Album;
    private javax.swing.JFrame Artist;
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton Lanzar_single;
    private javax.swing.JButton Publicar_album;
    private javax.swing.JPanel Single;
    private javax.swing.JTextField TITLE;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JFrame User;
    private javax.swing.JPanel artist;
    private javax.swing.JTextField artist_artisticname_field;
    private javax.swing.JButton artist_register;
    private javax.swing.JFormattedTextField artist_register_age1;
    private javax.swing.JPasswordField artist_register_password1;
    private javax.swing.JTextField artist_register_username1;
    private javax.swing.JPasswordField contra_field;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField field_duracion_single;
    private javax.swing.JTextField field_nombre_cancion_single;
    private javax.swing.JTextField field_title_single;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree_album_artista;
    private javax.swing.JTextField nombre_cancion;
    private javax.swing.JButton register_user;
    private javax.swing.JTabbedPane tabbedpanel;
    private javax.swing.JPanel user;
    private javax.swing.JFormattedTextField user_register_age;
    private javax.swing.JPasswordField user_register_password;
    private javax.swing.JTextField user_register_username;
    private javax.swing.JTextField usuario_field;
    // End of variables declaration//GEN-END:variables
}
